== Example Library Walkthrough

Let's say you had a simple pipeline template to support teams using
maven and ant as their build tools:

[source,]
----
unit_test()
build()
package() 
deploy_to dev 
----

A GitHub Repository called `jte-lib` located at
`https://github.com/jte-library-example/jte-lib.git` with the following
directory structure:

[source,]
----
maven/ 
    build.groovy
    package.groovy
    unit_test.groovy
    README.rst
ant/ 
    build.groovy
    package.groovy
    unit_test.groovy 
    README.rst
weblogic/
    deploy_to.groovy
    README.rst
glassfish/
    deploy_to.groovy
    README.rst
sonarqube/
    static_code_analysis.groovy
    README.rst
----

[IMPORTANT]
.Important
====
As a best practice, it is ideal to have a README in each library
directory that explains what the library does as well as any
configuration options for the library. With Booz Allen's
https://github.com/boozallen/sdp-libraries.git[Solutions Delivery
Platform JTE Libraries], we use sphinx to automatically compile the
library README.rst files into a published documentation github pages
site to communicate libraries developed and how to use them.
====

You would then configure this repository as a library source either
in the global Jenkins Templating Engine Configuration or in a Governance
Tier. This will make the libraries `maven`, `ant`, `weblogic`,
`glassfish`, and `sonarqube` accessible to be loaded.

Let's say one application is using Maven and deploying to a Weblogic
server.

Their configuration file could be:

[source,]
----
application_environments{
    dev{
        long_name = "Development" 
    }
}

libraries{
    maven
    sonarqube
    weblogic 
}
----

while an application using Ant and deploying to a GlassFish server would
have

[source,]
----
application_environments{
    dev{
        long_name = "Development" 
    }
}

libraries{
    ant
    sonarqube
    glassfish  
}
----

and in both instances, the applications would be using the same pipeline
template.
